name: GitHub App token
author: Thibault Derousseaux <tibdex@gmail.com>
description: Used to impersonate a GitHub App in a GitHub Action when secrets.GITHUB_TOKEN's limitations are too restrictive and a personal access token is not suitable.
inputs:
  app_id:
    description: ID of the GitHub App.
    required: true
  private_key:
    description: Private key of the GitHub App (can be Base64 encoded).
    required: true
outputs:
  token:
    description: An installation token for the GitHub App on the current repository.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: unlock
  color: gray-dark
